import { defineTool } from "@lovable.dev/mcp-js";
import { z } from "zod";

type GatewayImageResponse = {
  choices?: Array<{
    message?: {
      images?: Array<{ image_url?: { url?: string } }>;
      content?: string;
    };
  }>;
};

export default defineTool({
  name: "generate_product_photo",
  title: "Generate product ad photo",
  description:
    "Generate a premium, e-commerce ready product advertisement photo from a text prompt (and optional reference image data URL). Returns a PNG. Does not read or write any user data. Powered by GMAMIKO101 + Gemini.",
  inputSchema: {
    prompt: z
      .string()
      .min(3)
      .max(2000)
      .describe(
        "Description of the product ad to generate — subject, style, mood, background, lighting, etc.",
      ),
    reference_image_data_url: z
      .string()
      .startsWith("data:image/")
      .max(15_000_000)
      .optional()
      .describe(
        "Optional reference image as a data URL (data:image/png;base64,... or data:image/jpeg;base64,...). Used as the product to keep faithful.",
      ),
  },
  annotations: {
    readOnlyHint: false,
    idempotentHint: false,
    openWorldHint: true,
  },
  handler: async ({ prompt, reference_image_data_url }) => {
    const key = process.env.LOVABLE_API_KEY;
    if (!key) {
      return {
        content: [{ type: "text", text: "AI service not configured (missing LOVABLE_API_KEY)." }],
        isError: true,
      };
    }

    const systemHint =
      "You are producing a premium, e-commerce ready product advertisement image. Clean, high-end lighting, sharp focus, marketing quality. Never alter the product's logo, patterns, colors or textures.";

    const content: Array<Record<string, unknown>> = [
      { type: "text", text: `${systemHint}\n\nUser request: ${prompt}` },
    ];
    if (reference_image_data_url) {
      content.push({ type: "image_url", image_url: { url: reference_image_data_url } });
    }

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 60_000);

    try {
      const upstream = await fetch("https://ai.gateway.lovable.dev/v1/images/generations", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${key}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "google/gemini-3.1-flash-image",
          messages: [{ role: "user", content }],
          modalities: ["image", "text"],
          stream: false,
        }),
        signal: controller.signal,
      });

      if (!upstream.ok) {
        const text = await upstream.text().catch(() => "");
        if (upstream.status === 429) {
          return {
            content: [{ type: "text", text: "Rate limit reached — please retry shortly." }],
            isError: true,
          };
        }
        if (upstream.status === 402) {
          return {
            content: [
              {
                type: "text",
                text: "AI credits exhausted for GMAMIKO101 — the app owner must add credits.",
              },
            ],
            isError: true,
          };
        }
        return {
          content: [{ type: "text", text: `Upstream error ${upstream.status}: ${text || "unknown"}` }],
          isError: true,
        };
      }

      const data = (await upstream.json()) as GatewayImageResponse;
      const url = data.choices?.[0]?.message?.images?.[0]?.image_url?.url;
      if (!url || !url.startsWith("data:image/")) {
        return {
          content: [{ type: "text", text: "AI returned no image." }],
          isError: true,
        };
      }

      const match = url.match(/^data:(image\/[^;]+);base64,(.+)$/);
      if (!match) {
        return {
          content: [{ type: "text", text: "AI returned an unreadable image payload." }],
          isError: true,
        };
      }
      const [, mimeType, base64] = match;

      return {
        content: [
          { type: "image", data: base64, mimeType },
          {
            type: "text",
            text: "Product ad image generated by GMAMIKO101 (Gemini image).",
          },
        ],
      };
    } catch (err) {
      const aborted = err instanceof Error && err.name === "AbortError";
      return {
        content: [
          { type: "text", text: aborted ? "AI request timed out." : "AI service unreachable." },
        ],
        isError: true,
      };
    } finally {
      clearTimeout(timeout);
    }
  },
});
